### PR TITLE
Remove tsc from package.json

### PR DESCRIPTION
**Pull request by imnasnainaec**
The tsc in package.json (introduced in #724) causes a failure for me (Ubuntu 18.04) when running `npm start`:
```
> thecombine@0.2.0-alpha.1 predatabase /home/dror/sil/TheCombine
> tsc setupMongo.ts && node setupMongo.js

setupMongo.ts(5,37): error TS1005: ';' expected.
setupMongo.ts(6,9): error TS1005: ';' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! thecombine@0.2.0-alpha.1 predatabase: `tsc setupMongo.ts && node setupMongo.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the thecombine@0.2.0-alpha.1 predatabase script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/727)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/727)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[package.json, line 102 at r1](https://reviewable.io/reviews/sillsdev/thecombine/727#-MHmTUTI9tkmUUrW2Sfy:-MHmTUTI9tkmUUrW2Sfz:b-4bntn5) ([raw file](https://github.com/sillsdev/thecombine/blob/d2c4ba3bec778be96c0d847e927849d39a38b852/package.json#L102)):*
> ```
> "typescript": "^3.9.7"
> ```
I assume the ability to actually call 'tsc' comes from here right?

**Review by imnasnainaec — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/727)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @imnasnainaec)

___
*[package.json, line 102 at r1](https://reviewable.io/reviews/sillsdev/thecombine/727#-MHmTUTI9tkmUUrW2Sfy:-MHmkMch3jE53B5V7loZ:bp0rmc9) ([raw file](https://github.com/sillsdev/thecombine/blob/d2c4ba3bec778be96c0d847e927849d39a38b852/package.json#L102)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> "typescript": "^3.9.7"
> ```
I assume the ability to actually call 'tsc' comes from here right?
</blockquote></details>

Yes, I believe so.

**Review by jmgrady — APPROVED** [review]
Verified on Ubuntu 18.04 and Windows 10.

:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/thecombine/727#-:-MHw5RMnBp9w-ZICiXHN:bvz9vbp)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johnthagen** [comment]
Sorry, I had noticed this had been added to my PR, but thought it was needed by the reviewer. I will follow up on changes like this next time before PR is approved.
